development:
  adapter: postgresql
  encoding: utf8
  database: test_store_dev
  pool: 5
  username: mike
  password: mike
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: utf8
  database: test_store_test
  pool: 5
  username: mike
  password: mike
  host: 127.0.0.1
